# Meslo Nerd Fonts
add_newline = false
format = "[î‚¶](blue)[ïŒ“ ](bg:blue fg:black)$username$hostname[î‚¸](bg:purple fg:blue)$directory[î‚´](purple) \n$character\n"

[character]
error_symbol = "[îªœ](bold red)"
success_symbol = "[îªœ](bold green)"

[directory]
format = "[$path]($style)"
style = "bg:purple fg:black"
truncate_to_repo = false

[directory.substitutions]
Documents = "ğŸ“„ "
Downloads = "ğŸ“¥ "
Music = "ğŸœ "
Pictures = "ğŸ“· "

[hostname]
disabled = false
format = "[ ğŸŒ ](bg:blue fg:white)[$hostname](bg:blue fg:white)"
ssh_only = true

[username]
format = "[$user]($style)"
show_always = true
style_root = "bg:blue fg:red"
style_user = "bg:blue fg:black"
